"""Figure 8: the two-loop account, drawn as a hypothesis rather than a result.

THIS FIGURE IS SPECULATIVE AND IS LABELLED AS SUCH ON THE PAGE. It belongs to
the Ideas and speculation section, not to Results. Panels A and E are drawn
schematics; C and D carry measured values, and so does one feature of B -- the
theta-phase offset between the two gamma bands, which was measured rather than
assumed after an earlier version of the panel drew it wrong (see below).

The chain the figure makes, left to right, top to bottom:

    neuromodulatory tone  ->  which loop dominates  ->  which cells express it

    A   THE MOTIF AND THE GATE. Grid cells and fast-spiking interneurons form a
        recurrent loop; sensory afferents drive a feedforward one through the
        same interneurons; cholinergic tone sets the balance. The loop is not
        invented for this figure -- it is the one measured in Figure 4, where
        interneuron-to-grid is the strongest pathway in the dataset and the
        inhibitory limb is the slower of the two (3.0 against 1.0 ms).
    B   WHY TWO BANDS. Gamma is generated by the inhibitory limb, so loop
        kinetics set frequency: the slower recurrent loop gives slow gamma, the
        faster feedforward one fast gamma, each nested in theta. The states
        differ in which loop dominates, not in how much gamma there is. The
        phase offset between the bands is the one quantity in this panel that
        is MEASURED rather than drawn -- see gamma_theta_phase.py and the note
        beside it.
    C   THE FIELD POTENTIAL (measured, Figure 7).
    D   THE READOUT (measured, Figure 2): the cells that express the state are
        the two populations that constitute the loop, and no others.
    E   THE TEST that would settle the band assignment, marked untested.

WHAT THIS FIGURE DELIBERATELY DOES NOT DEPICT. Earlier versions of this account
located anchoring in the GRID PHASE -- the map pinned in the anchored state and
displaced, drifting, or reset to an arbitrary offset in the non-anchored one.
Every phase-level version is excluded by the data (see drift_vs_remap.py):
non-anchored trials have no coherent field at any offset once the
unrelated-cell floor is applied, no alignment between neighbouring trials, and
no gradient along the track. So nothing here shows a displaced grid bump, and
nothing here claims what the phase does on a non-anchored trial. The claim is
about which loop is running and what sets it, not about where the map sits.

Writes fig8_model.pdf
"""
import os

import matplotlib
import numpy as np

matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, FancyArrowPatch, FancyBboxPatch

plt.rcParams['font.family'] = 'Arial'
plt.rcParams['mathtext.fontset'] = 'custom'
plt.rcParams['mathtext.rm'] = 'Arial'
plt.rcParams['mathtext.it'] = 'Arial:italic'
plt.rcParams['mathtext.bf'] = 'Arial:bold'
plt.rcParams['pdf.fonttype'] = 42

FIG = os.path.dirname(os.path.abspath(__file__))
OUT = f'{FIG}/fig8_model.pdf'

SLOW = '#2b6cb0'      # slow gamma, as in Figure 7
FAST = '#c04744'      # fast gamma
THETA = '#7b4173'
GRID_C = '#c04744'
INT_C = '#2b6cb0'
ACH = '#b8860b'


def _lp(ax, s, dx=-.14, dy=1.0):
    ax.text(dx, dy, s, transform=ax.transAxes, fontsize=10, weight='bold',
            va='bottom', ha='left')


def arrow(ax, p0, p1, color, rad=0., lw=1.3, inhib=False, ls='-', shrink=9):
    """Excitatory (arrowhead) or inhibitory (bar) connection."""
    ax.add_patch(FancyArrowPatch(
        p0, p1, arrowstyle='-[' if inhib else '-|>',
        mutation_scale=5.5 if inhib else 8, lw=lw, color=color, linestyle=ls,
        shrinkA=shrink, shrinkB=shrink, zorder=3,
        connectionstyle=f'arc3,rad={rad}'))


fig = plt.figure(figsize=(9.5, 5.3))
outer = fig.add_gridspec(2, 1, height_ratios=[1.02, 1.0], hspace=.46,
                         left=.055, right=.985, top=.88, bottom=.085)
top = outer[0].subgridspec(1, 2, width_ratios=[1.34, 1.0], wspace=.20)
bot = outer[1].subgridspec(1, 3, width_ratios=[.92, .92, 1.04], wspace=.52)

# ── A: the motif and the gate ─────────────────────────────────────────────
ax = fig.add_subplot(top[0]); _lp(ax, 'A', dx=-.075)
ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis('off')
ax.set_title('the motif, as measured in Figure 4, and what sets it',
             fontsize=7.5, loc='left', color='0.25', pad=7)

ax.add_patch(FancyBboxPatch((.18, .32), .60, .42, boxstyle='round,pad=.035',
                            fc='#f4f1ec', ec='0.8', lw=.9, zorder=0))
ax.text(.48, .775, 'entorhinal cortex', fontsize=7, color='0.45', ha='center')

G, I = (.33, .53), (.63, .53)
ax.add_patch(Circle(G, .082, fc=GRID_C, ec='none', alpha=.85, zorder=2))
ax.add_patch(Circle(I, .082, fc=INT_C, ec='none', alpha=.85, zorder=2))
ax.text(*G, 'grid', fontsize=7, color='w', ha='center', va='center',
        weight='bold', zorder=4)
ax.text(*I, 'FS', fontsize=7, color='w', ha='center', va='center',
        weight='bold', zorder=4)

# grid -> FS excitatory on TOP, FS -> grid inhibitory BENEATH, each with its
# label on its own arc (negative rad puts the left-to-right arc above)
arrow(ax, G, I, GRID_C, rad=-.42)
arrow(ax, I, G, INT_C, rad=-.42, inhib=True)
ax.text(.48, .722, 'excites', fontsize=6.3, color=GRID_C, ha='center')
ax.text(.44, .305, 'inhibits — the slower limb', fontsize=6.3, color=INT_C,
        ha='center')
ax.text(.48, .205, 'recurrent loop', fontsize=7, color=SLOW, ha='center',
        weight='bold')

arrow(ax, (.985, .53), (.715, .53), FAST, lw=1.4, shrink=3)
ax.text(.885, .605, 'visual', fontsize=6.5, color=FAST, ha='center')
ax.text(.885, .455, 'afferents', fontsize=6.5, color=FAST, ha='center')
ax.text(.885, .372, 'feedforward', fontsize=6.3, color=FAST, ha='center',
        weight='bold')
ax.text(.735, .435, 'carries\nspeed', fontsize=6, color=INT_C, ha='center',
        style='italic', linespacing=1.25)

arrow(ax, (.48, .075), (.48, .275), ACH, lw=1.4, ls=(0, (2.4, 1.6)))
ax.text(.48, .028, 'septal cholinergic tone (MS/DBB), indexed by pupil (Figure 5)',
        fontsize=6.4, color=ACH, ha='center')
ax.text(.48, -.045, 'the one septal projection our nulls do not constrain',
        fontsize=5.8, color='0.45', ha='center', style='italic')

# ── B: why two bands ──────────────────────────────────────────────────────
ax = fig.add_subplot(top[1]); _lp(ax, 'B', dx=-.10)
ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis('off')
ax.set_title('loop kinetics set frequency', fontsize=7.5, loc='left',
             color='0.25', pad=7)

t = np.linspace(0, 2, 1400)
X = t / 2 * .84 + .11
th = np.sin(2 * np.pi * t)
# Each band rides on its own theta phase, and the OFFSET BETWEEN THEM IS
# MEASURED, not assumed: across 44 sessions slow gamma peaks at +94 deg of
# theta and fast gamma at +48 deg, a within-session difference of +45 deg
# (R = 0.87, Rayleigh p = 5e-15; see gamma_theta_phase.py). An earlier version
# of this panel drew them in ANTIPHASE, roughly 180 deg apart, which only 1 of
# 44 sessions comes near -- the separation is real but four times smaller than
# the schematic implied.
PHASE_OFF = np.radians(45.3)
e_fast = np.clip(np.cos(2 * np.pi * t), 0, None) ** 1.6
e_slow = np.clip(np.cos(2 * np.pi * t - PHASE_OFF), 0, None) ** 1.6
for row, (lab, a_slow, a_fast) in enumerate((('engaged — anchored', 1.00, .34),
                                             ('disengaged', .58, 1.00))):
    y0 = .620 - row * .345
    g = (a_slow * np.sin(2 * np.pi * 13 * t) * e_slow
         + a_fast * np.sin(2 * np.pi * 27 * t) * e_fast) * .055
    ax.plot(X, y0 + th * .052 + g, color='0.35', lw=.65, zorder=3)
    ax.plot(X, y0 + th * .052, color=THETA, lw=1.5, alpha=.5, zorder=2)
    ax.text(.11, y0 + .150, lab, fontsize=6.8, color='0.3')
    # which band sits where
    for cen, cl, nm in ((1.0 + PHASE_OFF / (2 * np.pi), SLOW, 'slow'),
                        (1.0, FAST, 'fast')):
        ax.text(cen / 2 * .84 + .11, y0 - .115, nm, fontsize=5.9, color=cl,
                ha='center')
ax.text(.11, .900, 'theta', fontsize=6.3, color=THETA)
ax.text(.37, .900, 'slow gamma', fontsize=6.3, color=SLOW)
ax.text(.70, .900, 'fast gamma', fontsize=6.3, color=FAST)
ax.text(.50, .030, 'the bands do not trade against one another:\n'
                   'each is modulated on its own',
        fontsize=6.3, color='0.45', ha='center', linespacing=1.35)

# ── C: the field potential (measured) ─────────────────────────────────────
ax = fig.add_subplot(bot[0]); _lp(ax, 'C', dx=-.46)
ax.set_title('what the field potential\ndoes (Figure 7)', fontsize=7.5,
             loc='left', color='0.25', pad=5)
val = [+0.105, -0.108, -0.094, -0.159]
lab = ['slow gamma\n30–48 Hz', 'fast gamma\n60–100 Hz', 'theta\n6–10 Hz',
       'theta–fast\ncoupling']
y = np.arange(len(val))[::-1]
ax.barh(y, val, color=[SLOW, FAST, THETA, FAST], alpha=.85, height=.62, lw=0)
ax.axvline(0, color='0.35', lw=.9, zorder=3)
for yy, v in zip(y, val):
    ax.text(v + (.012 if v > 0 else -.012), yy, f'{v:+.3f}', fontsize=6.3,
            va='center', ha='left' if v > 0 else 'right', color='0.25')
ax.set_yticks(y); ax.set_yticklabels(lab, fontsize=6.5)
ax.set_xlim(-.27, .20); ax.set_xticks([-.2, -.1, 0, .1])
ax.set_xlabel('anchored − non-anchored', fontsize=7)
ax.tick_params(labelsize=6.5); ax.spines[['top', 'right']].set_visible(False)

# ── D: the readout (measured) ─────────────────────────────────────────────
ax = fig.add_subplot(bot[1]); _lp(ax, 'D', dx=-.46)
ax.set_title('which cells express it\n(Figure 2)', fontsize=7.5, loc='left',
             color='0.25', pad=5)
val = [+0.119, +0.080, -0.000, -0.023]
lab = ['grid', 'putative\ninterneuron', 'non-grid\nspatial', 'non-spatial']
sig = ['p = 0.002', 'p = 0.0004', 'n.s.', 'n.s.']
y = np.arange(len(val))[::-1]
ax.barh(y, val, color=[GRID_C, INT_C, '0.72', '0.72'], alpha=.85, height=.62,
        lw=0)
ax.axvline(0, color='0.35', lw=.9, zorder=3)
for yy, v, s in zip(y, val, sig):
    ax.text(v + (.006 if v >= 0 else -.006), yy, s, fontsize=6.1,
            va='center', ha='left' if v >= 0 else 'right', color='0.25')
ax.set_yticks(y); ax.set_yticklabels(lab, fontsize=6.5)
ax.set_xlim(-.075, .185); ax.set_xticks([0, .05, .10, .15])
ax.set_xlabel('agreement above\nthe cell\'s own null', fontsize=7)
ax.tick_params(labelsize=6.5); ax.spines[['top', 'right']].set_visible(False)
ax.text(.0, -.40, 'the two populations that constitute the loop,\nand no others',
        transform=ax.transAxes, fontsize=6.3, color='0.45', linespacing=1.35)

# ── E: the test that would settle it ──────────────────────────────────────
ax = fig.add_subplot(bot[2]); _lp(ax, 'E', dx=-.10)
ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis('off')
ax.set_title('the test, not yet run', fontsize=7.5, loc='left', color='0.25',
             pad=5)
for x_, y_, w_, h_, nm, c_ in ((.30, .44, .30, .17, 'MEC', '#f4f1ec'),
                               (.02, .73, .34, .16, 'visual\ncortex', '#fbf0ef'),
                               (.02, .15, .34, .16, 'subicular\ncomplex', '#eef3fa')):
    ax.add_patch(FancyBboxPatch((x_, y_), w_, h_, boxstyle='round,pad=.022',
                                fc=c_, ec='0.75', lw=.9, zorder=1))
    ax.text(x_ + w_ / 2, y_ + h_ / 2, nm, fontsize=6.8, ha='center',
            va='center', color='0.3', linespacing=1.2)
arrow(ax, (.33, .72), (.42, .62), FAST, rad=-.25, lw=1.3, shrink=1)
arrow(ax, (.33, .32), (.42, .44), SLOW, rad=.25, lw=1.3, shrink=1)
ax.text(.64, .80, 'fast gamma\nshould cohere\nhere', fontsize=6.2, color=FAST,
        ha='left', va='center', linespacing=1.3)
ax.text(.64, .22, 'slow gamma\nshould cohere\nhere', fontsize=6.2, color=SLOW,
        ha='left', va='center', linespacing=1.3)
ax.text(.50, -.10, 'the slow/fast assignment is borrowed from\n'
                   'hippocampus; these sessions could earn it',
        transform=ax.transAxes, fontsize=6.3, color='0.45', ha='center',
        linespacing=1.35)

fig.text(.055, .955, 'HYPOTHESIS', fontsize=8, weight='bold', color='#8a1c1c')
fig.text(.163, .955, '— A and E are schematics; C, D and the band phase offset '
                     'in B are measured', fontsize=8, color='0.45')

plt.savefig(OUT, dpi=300, bbox_inches='tight')
plt.close(fig)
print(f'wrote {OUT}')
